# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/PracticalWork.Reports.Web/PracticalWork.Reports.Web.csproj", "src/PracticalWork.Reports.Web/"]
RUN dotnet restore "./src/PracticalWork.Reports.Web/PracticalWork.Reports.Web.csproj"
COPY . .
WORKDIR "/src/src/PracticalWork.Reports.Web"
RUN dotnet build "./PracticalWork.Reports.Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./PracticalWork.Reports.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PracticalWork.Reports.Web.dll"]
